#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import argparse
import subprocess

import libvirt
from lxml import etree

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Get IP address of a virtual machine')
    parser.add_argument('--system', action='store_true',
                        help='Use qemu:///system')
    parser.add_argument('vm_name',
                        help='Name of the virtual machine')

    args = parser.parse_args()

    target = None
    if args.system:
        target = 'qemu:///system'

    conn = libvirt.openReadOnly(target)
    if not conn:
        sys.stderr.write('Failed to open connection to the hypervisor\n')
        sys.exit(1)

    try:
        domain = conn.lookupByName(args.vm_name)
    except libvirt.libvirtError:
        sys.stderr.write('Domain not found, --system required?\n')
        sys.exit(1)

    desc = etree.fromstring(domain.XMLDesc(0))
    mac_address = (desc.find("devices/interface[@type='network']/mac")
                   .attrib["address"].lower().strip())

    arp_proc = subprocess.Popen(["arp", "-n"], stdout=subprocess.PIPE)
    (arp_stdout, arp_stderr) = arp_proc.communicate()

    for line in arp_stdout.splitlines()[1:]:
        parts = line.split()
        if parts[2] == mac_address:
            print(parts[0])
            sys.exit(0)

    sys.exit(1)
